import type { NextPage } from 'next'
import Head from 'next/head'
import cookie from "cookie"
import Image from 'next/image'
import { useCookies } from 'react-cookie'
import { useEffect, useState } from 'react'

const SignIn: NextPage = () => {
    const [, setCookie] = useCookies(["user"])
    const [username, setUsername] = useState("")
    const [password, setPassword] = useState("")

    const handleLogIn = async (username: string, password: string) => {
        try {
            if (!(username && password)) throw new Error("No username or password")

            const response = await fetch("http://localhost:3000/api/auth/signin", {
                method: "POST",
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    "username": username,
                    "password": password
                })
            })
            console.log(response)
            if (response.ok) {
                const data = await response.json()
                console.log(data)
                // setCookie("user", JSON.stringify(data), {
                //     path: "/",
                //     maxAge: 1653320965, // Expires after 1 month
                //     sameSite: true,
                // })
            } else {
                console.error("Error: ", response.statusText)
            }
        } catch (err) {
            console.log(err)
        }
    }

    return (
        <div>
            <Head>
                <title>Sign in - TimezoneDB</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>Creating a new user</h1>
            
            <label>
                Username:
                <input type="text" value={username} onChange={e => setUsername(e.target.value)} />
            </label>
            <label>
                Password:
                <input type="password" value={password} onChange={e => setPassword(e.target.value)} />
            </label>
            <button onClick={() => handleLogIn(username, password)}>Sign in</button>
        </div>
    )
}

SignIn.getInitialProps = async ({ req }) => {
    const data = cookie.parse(req ? req.headers.cookie || "" : document.cookie)

    return {
        data: data && data,
    }
}


export default SignIn
